name: meeting_room
description: A daily offline meeting planner flutter application.

publish_to: 'https://github.com/sad1996/meeting_room'

version: 1.0.0+1

environment:
  sdk: ">=2.10.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  get: ^3.24.0
  provider: ^4.3.3
  intl: ^0.16.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  flutter_local_notifications: ^3.0.3
  timezone: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true